development:
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_CLIENT_SECRET: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

production:
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_CLIENT_SECRET: <%= ENV["GOOGLE_CLIENT_SECRET"] %>